trading_calendars/trading_calendar.py, trading_calendars/utils/pandas_utils.py, trading_calendars/utils/preprocess.py
Move `coerce` and `days_at_time` to `trading_calendars.utils`
=> MAINT: move utils to trading_calendars.utils

etc/check_holidays.py
Adds a script for comparing the holidays in a trading calendar against a CSV key.
=> DEV: Add check_holidays.py

README.md
correct the Shanghai Stock Exchange website.
=> Shanghai Stock Exchange website

trading_calendars/trading_calendar.py
- Fix missing typo in error message
=> Fix missing typo in error message

etc/tcal
This is useful for annotating unit tests which depend on unfamiliar trading calendars.
example usages:
```
$ ./etc/tcal XTKS 01 2014
January 2014
Su  Mo  Tu  We  Th  Fr  Sa
[ 1][ 2][ 3][ 4]
[ 5]  6   7   8   9  10 [11]
[12][13] 14  15  16  17 [18]
[19] 20  21  22  23  24 [25]
[26] 27  28  29  30  31 
```
```
$ ./etc/tcal XTKS 2014
2014
January                        February                        March
Su  Mo  Tu  We  Th  Fr  Sa     Su  Mo  Tu  We  Th  Fr  Sa     Su  Mo  Tu  We  Th  Fr  Sa
[ 1][ 2][ 3][ 4]                           [ 1]                           [ 1]
[ 5]  6   7   8   9  10 [11]   [ 2]  3   4   5   6   7 [ 8]   [ 2]  3   4   5   6   7 [ 8]
[12][13] 14  15  16  17 [18]   [ 9] 10 [11] 12  13  14 [15]   [ 9] 10  11  12  13  14 [15]
[19] 20  21  22  23  24 [25]   [16] 17  18 …
```
=> DEV: add tcal script to generate cal-like trading calendars

.travis.yml
Pin to working version of conda
=> Conda install that works

README.md, trading_calendars/calendar_utils.py, trading_calendars/exchange_calendar_xwar.py
Added Poland Stock Exchange XWAR calendar with Holidays
=> Added Poland Stock Exchange XWAR calendar

etc/requirements_lunisolar.txt
A more recent verison is pinned in requirements.txt.
=> DEV: Remove stale toolz requirement

setup.py, trading_calendars/tcal.py
Takes @llllllllll 's script and packages it as a console entry point so after pip installing it is possible to call:
```
➜  dev tcal XTKS 01 2014
January 2014
Su  Mo  Tu  We  Th  Fr  Sa
[ 1][ 2][ 3][ 4]
[ 5]  6   7   8   9  10 [11]
[12][13] 14  15  16  17 [18]
[19] 20  21  22  23  24 [25]
[26] 27  28  29  30  31
```
=>  Package tcal as a real entry point

trading_calendars/exchange_calendar_bvmf.py
=> MAINT: Update trading hours in Brazilian Stock Exchange

trading_calendars/utils/preprocess.py
=> Fix compatibility with python 3.8 and PEP 570

.travis.yml
Closes https://github.com/quantopian/trading_calendars/issues/111
=> Removed unused coveralls

.pre-commit-config.yaml
[pre-commit](https://pre-commit.com) hook is a good tool to improve code quality and automatic testing. I've added a small and out-of-the-box list of hooks. Any suggestions?
=> Introducing pre-commit hook

setup.cfg
Attempt to solve https://github.com/quantopian/trading_calendars/issues/118
=> BLD: Try traverse-namespace

.github/workflows/main.yml, .github/workflows/master-merge.yml, .github/workflows/release.yml, tests/test_trading_calendar.py
=> BLD/MANT: Update test coverage and fix build process

.github/release-drafter-config.yml, .github/workflows/labeler.yml, .github/workflows/main.yml, tests/test_trading_calendar.py
Also closes https://github.com/quantopian/trading_calendars/issues/145
=> BLD: Add PR labeler, bump pandas/numpy in testing

tests/test_trading_calendar.py, trading_calendars/exchange_calendar_iepa.py, trading_calendars/exchange_calendar_xbog.py, trading_calendars/exchange_calendar_xnys.py, trading_calendars/us_futures_calendar.py, trading_calendars/utils/pandas_utils.py
Closes https://github.com/quantopian/trading_calendars/issues/156
=> MAINT: Replace US/Eastern with America/New_York

trading_calendars/calendar_utils.py
some more market standard exchange aliases
=> ENH: add additional aliases

README.md
Until we can write up real documentation, I wanted to update the Readme a bit more with basic usage.
=> DOC: Expand usage examples in README

etc/requirements.in, etc/requirements_locked.txt, etc/requirements_locked_old.txt, setup.py
Found in https://github.com/conda-forge/trading-calendars-feedstock/pull/1
=> Added missing direct dependencies to install_requires

.devcontainer/devcontainer.json, .github/workflows/benchmark.yml, .github/workflows/main.yml, etc/bench.py, etc/requirements_dev.in, etc/requirements_locked.txt, etc/requirements_locked_old.txt, setup.py
Closes https://github.com/quantopian/trading_calendars/issues/180
cc @llllllllll if you want to use this for anything. 
Right now I'm testing the constructuction of all of our calendars (which is our slowest test), but I'm open to other suggestions of what we should alert on.
=> BENCH: Add CI benchmarking and alerting on regressions

.github/dependabot.yml, .github/workflows/main.yml, etc/requirements_locked.txt
=> TST: Add py3.9 to test matrix
